version: '3'
services:
  stubby:
    image: "db260179/stubby:latest"
    container_name: stubby
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8053"
    networks:
     - dns
    restart: unless-stopped
    volumes:
      - ./stubby/stubby.yml:/opt/stubby/etc/stubby/stubby.yml:ro
  unbound:
    image: "db260179/unbound:1.14.0-stubby"
    container_name: unbound
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "stubby"    
    ports:
     - "53:53/udp"
     - "53:53/tcp"
    networks:
     - dns
    volumes:
      - ./unbound/a-records.conf:/opt/unbound/etc/unbound/a-records.conf:ro
    restart: unless-stopped

networks:
  dns:
